<?php

// DO NOT EDIT THIS FILE, MAKE EDITS IN THE .env!!

/*
 * This file is part of uhin/laravel_api.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [

    'pager_duty' => [
        'api_key'           => env('PAGER_DUTY_API_KEY', null),
        'integration_key'   => env('PAGER_DUTY_INTEGRATION_KEY', null),
        'url'               => env('PAGER_DUTY_URL', 'https://events.pagerduty.com/v2/enqueue'),
        'client'            => env('PAGER_DUTY_CLIENT', config('app.name')),
        'severity'          => env('PAGER_DUTY_SEVERITY', 'info'),
        'action'            => env('PAGER_DUTY_ACTION', 'trigger'),
    ],

    'rabbit' => [
        'host'                  => env('RABBIT_HOST', '127.0.0.1'),
        'port'                  => env('RABBIT_PORT', 5672),
        'username'              => env('RABBIT_USERNAME', null),
        'password'              => env('RABBIT_PASSWORD', null),
        'exchange'              => env('RABBIT_EXCHANGE', null),
        'routing_key'           => env('RABBIT_ROUTING_KEY', null),
        'queue'                 => env('RABBIT_QUEUE', null),

        // Optional rabbit connection properties
        'vhost' => env('RABBIT_VHOST', '/'),
        'insist' => env('RABBIT_INSIST', false),
        'login_method' => env('RABBIT_LOGIN_METHOD', 'AMQPLAIN'),
        'login_response' => env('RABBIT_LOGIN_RESPONSE', null),
        'locale' => env('RABBIT_LOCALE', 'en_US'),
        'connection_timeout' => env('RABBIT_CONNECTION_TIMEOUT', 3.0),
        // read_write_timeout must be at least double the heartbeat value
        'read_write_timeout' => env('RABBIT_READ_WRITE_TIMEOUT', 3.0),
        'context' => env('RABBIT_CONTEXT', null),
        'keepalive' => env('RABBIT_KEEPALIVE', false),
        'heartbeat' => env('RABBIT_HEARTBEAT', 0),
    ],

];
